### ISSUE TITLE
削除バッファとクリップボードをちゃんと同期する

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#161]
xyzzy の activate/deactivate 時に中途半端に同期するだけじゃなくて
リアルタイムに同期する。
### 背景
- kill した内容を grep-dialog などに貼りつけようとしてもできない
- VMware などを利用しているとホスト OS 側のアプリとゲスト OS 上の xyzzy とで
  クリップボードの共有がうまくできない
  - 例)
    1. ゲスト OS 上の xyzzy で kill
    2. ホスト OS に切り替え
    3. ホスト OS 上のブラウザにペースト
  - ホスト・ゲスト間のクリップボードの同期はできているが、
    ホスト・ゲスト切替時に xyzzy が deacitivate されないため xyzzy には反映されないため
### 仕様
- クリップボードが変更された時に実行するフック (`*change-clipboard-hook*`) を追加
- 完全に同期と中途半端に同期は従来からある `*sync-kill-ring-with-clipboard*` 変数で制御
  - `t` なら中途半端に同期
  - `:always` なら完全に同期
  - `nil` なら同期しない
  - ツール→さまざまで設定可能にする
- 中途半端に同期の場合の処理（従来の処理）
  - xyzzy が deactivate したときに kill-ring の内容の方が新しければ
    クリップボードにコピー
  - xyzzy で yank したときにクリップボードの内容の方が新しければ
    kill-ring にコピー
- 完全に同期を選んだ場合の処理
  - copy-region-as-kill で kill-ring からクリップボードに即コピー
  - `*change-clipboard-hook*` でクリップボードから kill-ring に追加
### 参考
- [クリップボードの内容をリアルタイムに取得するには？［C#、VB］ － ＠IT](http://www.atmarkit.co.jp/fdotnet/dotnettips/848cbviewer/cbviewer.html)
- 中途半端に同期するメリット

```
153名無しさん＠お腹いっぱい。sage2007/11/26(月) 11:50:51 ID:kzEu5Uvi0
中途半端に同期は慣れて来ると完全同期よりはるかに便利 
Emacsに誰か移植してくれんかなあ
154名無しさん＠お腹いっぱい。2007/11/26(月) 14:17:55 ID:9BDJHfoG0
中途半端だとどういうときに便利なの？ 
俺は今までそう思ったことないよ
155名無しさん＠お腹いっぱい。sage2007/11/26(月) 21:06:56 ID:vzMHw+4t0
そもそもあれって何をもって「中途半端」と命名されてるの
156名無しさん＠お腹いっぱい。sage2007/11/27(火) 00:51:20 ID:A1CLZXk80
削除バッファの内容が更新されてもクリップボードの内容へ即座に反映されたり 
はしないみたい。 
xyzzyのソースコード見てないからよく知らんけど、xyzzyのウィンドウが 
アクティブになったり非アクティブになったりするタイミングで更新されてたり 
するんじゃないかなあ。 

xyzzyの外部でクリップボードにコピーしてから、xyzzyのバッファを 
ちょくちょくいじって Shift+Insert で貼り付け、というのが出来てちょっと便利。 
（バッファいじるときにクリップボードの内容が破壊されない、という話。）
157153sage2007/11/27(火) 02:10:08 ID:dJXbb9La0
>>156 
そうそう、まさにそれ！ 
他のプログラムから取ってきたのを 
Emacsで新しくファイル開いて貼り付けようとしたら 

無意識のうちにパスをKillしちゃっててげんなりするんだけど 
xyzzyだとそれがない 

それに便利なのは編集中にkill か selection -> copy するのを使い分ければ 
一時保管領域を2個同時に使えて嬉しいんだよね 
もちろん region が正統派なんだろうけど俺にはこれがよく合うのよ
158名無しさん＠お腹いっぱい。sage2007/11/27(火) 04:23:05 ID:Y9pgIDx10
俺も２個目の一時保存バッファとして使ってるな。 
kill-ringをさかのれば良いと言われるとその通りなんだけど。
159名無しさん＠お腹いっぱい。sage2007/11/27(火) 05:52:35 ID:qHIOEO6N0
copy-to-clipboard に kill-new を引っかけたり、 
適当なタイミングで >>150 みたいなのを呼ぶようにしたりして 
kill-ring とクリップボードを完全同期にして使ってるのは俺だけかね。 
まあ各自使いやすいスタイルで使えば良いと思うけどさ。
160名無しさん＠お腹いっぱい。sage2007/11/27(火) 12:01:40 ID:NNiH/VWr0
同期しないで別々に使ってる。 
xyzzy の中だけならほとんど kill-ring しか使わない。 
たまにしばらく取っておきたい文字列があるとレジスタに。
161名無しさん＠お腹いっぱい。sage2007/11/27(火) 13:29:13 ID:d7SGse2I0
レジスタ = クリップボード？
162名無しさん＠お腹いっぱい。sage2007/11/27(火) 13:44:30 ID:CCKsojsL0
レジスタ 
ttp://www2.ocn.ne.jp/~cheerful/script/xyzzy/textEditor/register.html
```

xyzzyの使い方が分からぬやし 励ましあえ その11
http://www.bookshelf.jp/2ch/software/1191681847.html#153

**Comment by akawaguc** [comment]
この機能、使いたいです。

**Comment by x022235** [comment]
![クリップボードの同期設定画面](https://f.cloud.github.com/assets/1522408/572539/8abdd8b8-c79d-11e2-9ee1-1d119db291a4.png)

**Comment by akawaguc** [comment]
ご対応ありがとうございます。
クリップボードを多用するユーザにとっては嬉しい機能だと思います。
今のところ問題なく動いています。
