### ISSUE TITLE
DEP を有効にする

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#175]
### 背景
- 現状は DEP が有効だと `defun-c-callbale` とかでコールバックされると
  落ちてしまうので DEP を無効にしている (/NXCOMPAT:NO)
- 落ちないように修正した上で DEP を有効にする
### 参考
- https://bitbucket.org/mumurik/xyzzy/wiki/%E9%9B%91%E8%A8%98#!20120323
- [Memory Protection Constants](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366786.aspx)

**Comment by mumurik** [comment]
これってどの位の優先度ですかね？
待ってたら治るなら待ってcherry pickさせてもらおうかなぁ、と思ってますが。

**Comment by x022235** [comment]
マイルストーンが BluePrint なのは優先度低めです。
というかこちらが cherry pick させてもらおうと考えてました :-)

**Comment by mumurik** [comment]
了解です。
じゃあこっちでやりますか。
