### ISSUE TITLE
拡張子 .lisp のサポート

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#177]
### 背景
- xyzzy では Lisp ソースの拡張子として `*.l` を使うことになっている
- CL では `*.lisp` を使うことが多く、移植時に拡張子の変更が面倒である
- `*.l` は GitHub 上で色がつかなくて寂しい
### 対応
- `*.l*` に加えて `*.lisp` をサポートする
- `byte-compile` した場合は `*.lc` のままとする
- `require` や `load-library` では `*.lc` → `*.l` → `*.lisp` の順にファイルを探す
- `(compile-file-pathname "a.lisp")` => `a.lc`
- `(compile-file-pathname "a.l")` => `a.lc`
- `(compile-file-pathname "a.txt")` => `a.txt.lc`
- `*.lisp` ファイルを開いた場合も `lisp-mode` にする

**Comment by southly** [comment]
生成するバイトコードが変わらないのであれば、拡張子は同一の方がいいと思うのですがいかがでしょう。
つまり、このようにするということですが。
- `(compile-file-pathname "a.lisp")` => `a.lc`

**Comment by x022235** [comment]
確かに `*.lc` まで変える意味はなかったですね。
ご指摘の通りにします。
