### ISSUE TITLE
UNC パス対応

### ISSUE THREAD

**Issue by southly** [xyzzy-022/xyzzy#209]
カレントディレクトリが UNC パスの場合、cmd.exe が起動できないので、
適当な場所にカレントディレクトリを移してから起動するように修正する必要があります。
- http://hisashim.livejournal.com/215556.html
- http://support.microsoft.com/?scid=kb%3Ben-us%3B156276&x=15&y=11

**Comment by x022235** [comment]
ありがとうございます。以下のようにしようと思います。
- `ed:filter-region` でも同じ問題があるので、 `ed::shell-command-line` で対応する
  - `ed::shell-command-line` で `dir` が UNC パスだったら、
    起動ディレクトリとして `(get-windows-directory)` を返す
  - UNC パスで cmd.exe を起動した場合、余計なメッセージを出しつつ
    `C:\Windows` をカレントディレクトリとして起動するので互換性は保たれる
  - 余計なメッセージが出ているから `ed::diff-scan` がエラーになっていた
- `call-process`, `make-process` では特に何もしない
  - UNC パスをサポートしているかどうかはコマンドによるので、
    適切な `:exec-directory` を指定するのは呼び出し側の責任
