### ISSUE TITLE
locally 特殊形式の実装

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#271]
PCL のブート (#75) に必要なので locally を実装する。
＃PCL を書き換えれば locally なしでも大丈夫だとは思うが、素直に locally を実装する
### マクロによる参考実装

``` lisp
(defmacro locally (&body body)
  (multiple-value-bind (decls body)
      (lisp::find-declaration body)
    (let ((special-vars (mapcan #'(lambda (decl)
                                    (when (eq (car decl) 'special)
                                      (cdr decl)))
                                (cdar decls))))
      (if special-vars
          `(let (,@(mapcar #'(lambda (var)
                               `(,var (when (boundp ',var )
                                        (symbol-value ',var))))
                           special-vars))
             (declare (special ,@special-vars))
             ,@body)
        `(progn ,@body)))))
```

＃CLHS には特殊形式って明確に書いてあるのでマクロじゃダメ？
＃special-form-p が nil を返すと困る人がいる？
＃lisp レベルで特殊形式は実装できないんだっけか？
### 仕様
- [CLHS: Special Operator LOCALLY](http://clhs.lisp.se/Body/s_locall.htm)

**Comment by southly** [comment]
スペシャルフォームをマクロで実装するのはＯＫのはずです。
CLtL2 の 「5.1.3 特殊形式」の章でそういうことが書いてありました。

**Comment by x022235** [comment]
ありがとうございます。このあたりですね。

> An implementation is free to implement as a macro any construct described herein as a special form. Conversely, an implementation is free to implement as a special form any construct described herein as a macro if an equivalent macro definition is also provided. The practical consequence is that the predicates macro-function and special-form-p may both be true of the same symbol. 

他にも調べた限りでは以下のように理解しました。
間違っている点があれば指摘していただけるとありがたいです。
- special form を macro として実装してもいい
- macro を special form として実装してもいい
- macro を special form として実装する場合は、macro-function でマクロを展開できないといけない
- special-form-p が t を返すのは CLtL2 で定義された 25 個のシンボルに対してのみ
  - special form を macro で実装した場合は、special-form-p は t を返さないといけない
  - macro を special form で実装した場合は、special-form-p は nil を返さないといけない
  - xyzzy では以下が special form として実装されており (これは問題ない)、 special-form-p が t を返すがこれは ANSI CL に準拠していない。また、macro-function が nil を返すのも問題。
    - system:*byte-code 
    - interactive 
    - multiple-value-bind 
    - multiple-value-setq 
    - save-excursion 
    - save-restriction 
    - save-window-excursion 

---

参考文献:
- [5.1.3. Special Forms](http://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node59.html)
- [Bug #777473 “SPECIAL-OPERATOR-P should return true only for the ...” : Bugs : SBCL](https://bugs.launchpad.net/sbcl/+bug/777473)
- [comp.lang.lisp: Re: what are allowed special forms? (CLHS clarification)](http://coding.derkeiler.com/Archive/Lisp/comp.lang.lisp/2005-01/0817.html)
- [CLHS: Section 3.1.2.1.2.1](http://www.lispworks.com/documentation/lw50/CLHS/Body/03_ababa.htm)

**Comment by x022235** [comment]
バイトコンパイルにはまだ対応していない。
難しい。。。
