### ISSUE TITLE
zipball をビルドできない (.gitattributesの追加)

### ISSUE THREAD

**Issue by southly** [xyzzy-022/xyzzy#284]
こちらでも以下を採用してください。
- https://github.com/mumurik/xyzzy/pull/50

> zipで拾ったりしたときにバッチファイルが実行できなかったので…
> 
> slnとかvc_proj_とか、色々あるとは思いますが、とりあえず最低限あれば良いだろうと思ってます。
> - このコミットでは改行コードは変更されず、これ以後のコミットでCRLFになるようです
> - GitHub上で過去にさかのぼって適用する方法もあるのかな？？
### 参考
- [改行コード LF で日本語を含むバッチファイルの動作がおかしい件 - miauの避難所](http://d.hatena.ne.jp/miau/20100929/1285768041)

**Comment by x022235** [comment]
純粋な疑問なんですが、git を使わずにわざわざ zipball を使うってどういう状況なんでしょうか。

あと、ビルドができればそれで良くて *.l やキーワードファイルは LF のままでも
気にしないんでしょうか？

**Comment by x022235** [comment]
以下のようにしました。
- zipball も一応ビルできるようにする
  - ただし、zipball では *.l やキーワードファイルが LF のままなので
    ここからは正しいリリース物件を作成できない
- dist.bat でソースのアーカイブも作成しアップロードする
  - zipball ではなくこれをビルドすればリリース物件と同じものができる

**Comment by southly** [comment]
ありがとうございます。

*.l やキーワードファイルにCRLFでなければならないという制限は無いので、
ビルドの後の使用まで問題ないはずです。
実際自分でビルドして使っているxyzzyは全部LFですし。

自分の普段のgitの設定が `core.autocrlf=input` で、
今までxyzzyのビルドもこの設定で問題なかったので
そのままバッチファイルを使ってビルドしようとしてアレっということになったという経緯です。

**Comment by x022235** [comment]
> 自分の普段のgitの設定が core.autocrlf=input で、

なるほど。必要性が理解できました。
