### ISSUE TITLE
XMLファイル・エンコーディング自動判定処理の改善

### ISSUE THREAD

**Issue by akawaguc** [xyzzy-022/xyzzy#339]
まずxyzzyをメンテナンスしてくださっている方々にお礼を申し上げたいです。素晴らしいエディタのご提供をありがとうございます。

さて、最近のxyzzyはエンコーディングの自動判定処理が改善されてきていますが、XMLファイルについては、改善の余地があると思っています。

XMLファイルは、その仕様上、エンコーディングが明確に決まっています。
例：
    <?xml version="1.0" encoding="utf-8" standalone="yes"?> （後略）
    <?xml version="1.0" encoding="Shift_JIS" standalone="yes"?> （後略）

しかし現状のxyzzyはXMLファイル向けの特別な自動判定処理をしていないため、一部のXMLファイルに関して、自動判定ミスが出ることがあるように見えます。

XMLは見づらいところもありますが、現状ではよく使われているフォーマットの1つであるため、特別な自動判定処理を追加して頂けますと嬉しいです。

**Comment by x022235** [comment]
xml は確かによく使われているので XML 宣言に対応するようにします。

＃最初、[xml-mode](http://chez-sugi.net/xyzzy/xml-mode.html) に同様の機能があった気がしてたんですが、
＃ファイル保存時に変換してくれるのみなんですね（知らなかった・・・）

**Comment by snmsts** [comment]
とりあえず参考。
http://www.w3.org/TR/xml/#charencoding
http://www.w3.org/TR/xml/#sec-guessing

utf-8以外でxmlを書くのはナンセンスだと思う個人的な気持は置いておくとして、(運用の話では例外は山程というのは理解しております)
真っ当にエンコーディング指定をよみこむまでのエンコーディングを決める手掛かりとして
xmlファイルの初っ端は"<"で始まるものと見做してよいものなんですかね?

**Comment by x022235** [comment]
> 真っ当にエンコーディング指定をよみこむまでのエンコーディングを決める手掛かりとして
> xmlファイルの初っ端は"<"で始まるものと見做してよいものなんですかね?

あまり難しいことは考えてなくて `ed::find-file-scan-params` と同じように処理するつもりです。
- `insert-file-contents` で先頭 4K バイトを読み込む。この時点で xyzzy による自動判別が動く。
- あとは適当に `scan-buffer` してファイルで指定されたエンコーディングが見つかれば、そのエンコーディングで開く。
- BOM なしの UTF-16 の場合は自動判別できないので特別に処理する。
