### ISSUE TITLE
時々~xyz*.tmpというファイルが残る

### ISSUE THREAD

**Issue by akawaguc** [xyzzy-022/xyzzy#358]
xyzzyの動きについて2点質問です：
1. xyzzyを使っていると、時々~xyz*.tmp（例：~xyz8gcs.tmp）というファイルが生成され、xyzzy終了後も残ることがあるように感じるのですが、これは確かでしょうか。
2. もし1の通りである場合、~xyz*.tmpファイルの目的と、生成しない方法があれば教えて頂けますでしょうか。

**Comment by x022235** [comment]
ファイル IO 中に xyzzy が異常終了した場合や `:if-exists :rename` を指定して
ファイル IO している場合は残るのでそれかもしれないです。

xyzzy ではファイルを書き込するときは以下の手順で処理しています。
1. 一時ファイルを作成してファイルに書き込む
2. 書き込みが正常に完了した場合は元のファイル名にリネームする。
     正常に完了しなかった場合は一時ファイルを削除する

目的はファイルに書き込んでいる最中に異常終了した場合に、
元のファイルが書き込み途中で壊れないようにするためだと思います。

常に .tmp ファイルを作らないようにする全体的な設定はないようです。

個別に .tmp ファイルを作らないようにするには `open` の引数に `:if-exists :overwrite` を指定します。

例:

``` lisp
(with-open-file (s "test.txt" :direction :output
                   :if-exists :supersede
                   :if-does-not-exist :create)
  (princ "hoge" s)
  ;; ここで Ctrl-g で中断すると:
  ;; * :if-exists :overwrite の場合は
  ;;   test.txt に hoge だけが書かれた中途半端な状態になる
  ;; * :overwrite を指定しない場合や :new-version や :supersede の場合は
  ;;   test.txt は作成されない
  (sit-for 100)
  (princ "hoge" s))
```

**Comment by x022235** [comment]
Emacs には`file-precious-flag` というのがあるみたいだからこれを移植しましょうか。
今までの xyzzy の動作と合わせるためデフォルト値は Emacs とは異なって `t` になります。

> Variable: file-precious-flag
> 
> この変数がnil以外ならば、 save-bufferは保存処理中の入出力エラーに備えて対処する。 つまり、目的の名前のファイルにではなく一時的な名前の新規ファイルに書き出し、 エラーがないことを確認してから目的の名前に改名する。 これにより、不正なファイルに起因する問題からディスク容量の不足といった 問題を回避できる。
> 
> 副作用として、バックアップも必然的にコピーして行う。 see section 25.1.2 改名によるバックアップかコピーによるバックアップか。 それと同時に、大事な（precious）ファイルとして保存すると、 読者が保存したファイルと別のファイル名とのあいだの ハードリンクをつねに切ってしまう。
> 
> 特定のバッファではこの変数にnil以外のバッファローカルな値を 指定するモードもある。

[GNU Emacs Lispリファレンスマニュアル: Saving Buffers](http://www.geocities.co.jp/SiliconValley-Bay/9285/ELISP-JA/elisp_372.html#SEC373)

**Comment by akawaguc** [comment]
早速のコメントありがとうございます。

> Emacs にはfile-precious-flag というのがあるみたいだからこれを移植しましょうか。

恐れ入ります。
できましたらよろしくお願いいたします。

**Comment by x022235** [comment]
とりあえず `file-precious-flag` を追加しました。
- `save-buffer` で保存する場合のみ効果があります。
- `open` とかで直接ファイルを読み書きしてる場合は、`file-precious-flag` に関係なく引数によってバックアップファイルが作成するかどうかが決まります。

**Comment by akawaguc** [comment]
早速ありがとうございます！
次回リリースが待ち遠しいです。
