### ISSUE TITLE
Windows8 RTMで共通設定フォントタブが表示されない

### ISSUE THREAD

**Issue by yasuoohno** [xyzzy-022/xyzzy#363]
Windows8 RTMでxyzzy起動後にツール→共通設定を開くとフォントタブが表示されません。

一度ダイアログを閉じた後、再度共通設定を開くと、
フォントのタブが存在しますがタブを選択すると消えてしまいます。
（二度目のダイアログ起動では、前回のダイアログ表示によりフォントタブがデフォルトでは
選択されていない状態となっていますので、フォントタブを選択すると消えてしまうようです）

Versionは0.2.2.244で確認しています。

-フォント、Windows8で検索かけてみたのですが未報告のようでしたのでIssue登録させていただきました。
-マナー違反等ありましたら申し訳ございませんが、ご指摘いただければと思います。

**Comment by x022235** [comment]
報告ありがとうございます。修正しました。

Windows8 周りは確認しないといけないなと思いつつ放置していたので助かります。
