### ISSUE TITLE
ファイラ上で任意のフォルダを非表示にしたい

### ISSUE THREAD

**Issue by akawaguc** [xyzzy-022/xyzzy#368]
ファイラ上で、もし任意のディレクトリを非表示にできますと、すごく便利なのですが、可能でしょうか。

UNIX/LinuxからWindows上へ移植されたアプリケーションの中には、よくドットで始まるディレクトリを自動的に作成する物があります。また、そうでないアプリケーションの中にも、ホームディレクトリの中に邪魔なディレクトリを作る物がありますので、このような状況に対応したいです。

ディレクトリではなく、ドットファイルについては、次の様なlispで対応できるのですが、同じような事がディレクトリについても対応できるかどうかを知りたいです。

``` lisp
(pushnew '("dot ファイル以外" "[^.]*") *filer-path-masks* :test 'equal)
(pushnew '("dot ファイル" ".*") *filer-path-masks* :test 'equal)
```

**Comment by x022235** [comment]
[ソースを見ると](https://github.com/xyzzy-022/xyzzy/blob/v0.2.2.245/src/filer.cc#L185) `*filer-path-masks*` (C++ レベルでは`fv_masks`) はファイルにしか適用されないので本体の修正が必要ですね。

`*filer-path-masks*` がいきなりディレクトリにも適用されるようになるとびっくりする人もいるでしょうから、
どういう仕様にするかちょっと考えます。

**Comment by akawaguc** [comment]
早速のご返信ありがとうございます。

> `*filer-path-masks*` がいきなりディレクトリにも適用されるようになるとびっくりする人もいるでしょうから、
> どういう仕様にするかちょっと考えます。

ファイラの下位互換性を保つ別の案としましては、NTFSの「隠しファイル属性が付いているファイルとディレクトリを隠す」オプションを設定画面に追加し、これをファイラで実装する方法はいかがでしょうか。この場合、正規表現によるファイル名のフィルタリングはせず、隠したいファイルに都度隠しファイル属性を付ける必要がありますが、代替案にはなります。

**Comment by x022235** [comment]
> NTFSの「隠しファイル属性が付いているファイルとディレクトリを隠す」オプションを設定画面に追加

いいですね。エクスプローラにも同じようなオプションがありますし分かりやすそうですね。
＃C:\$Recycle.Bin とか表示されるのが気になってました。

**Comment by x022235** [comment]
![filer-setting](https://f.cloud.github.com/assets/1522408/34233/2f998aac-5107-11e2-8452-409b0467a0b2.png)

**Comment by akawaguc** [comment]
遅くなりましたが、ご対応ありがとうございました。
私の期待通りの動作である事を、本日確認しました。
