### ISSUE TITLE
Wineでの日本語フォント設定

### ISSUE THREAD

**Issue by rapidexp** [xyzzy-022/xyzzy#386]
これはWineのWindows再現力の問題なのでアプリ側に提案するのは筋違いですが、もし心当たりがあることで対応可能ならと思いレポートします。

現象: Wine上でxyzzyでは日本語が文字化けし、アプリケーション起動のたびに毎回フォント設定をし直さなければなりません。
原因: フォント一覧において同名の欧文フォントと日本語フォントが２つ並び欧文フォントが先のため、保存されたフォント名をxyzzyが読み取っただけでは日本語になりません。

![xyzzy-font-settings-1](https://f.cloud.github.com/assets/1854176/377388/bc862ab4-a4a5-11e2-8629-cceef6e368c6.png)

xyzzyでは文字セットの指定をフォント一覧に反映させていない仕様であることが、何か影響しているのではないでしょうか。以下はWindows上でのNotepadとxyzzyです。

![xyzzy-font-settings-2](https://f.cloud.github.com/assets/1854176/377398/616460e0-a4a7-11e2-8d6e-a7e3670920ad.png)

通常アプリケーションでは文字セットの変更がフォント一覧に影響しますが、xyzzyではフォント一覧は日本語フォントに固定、もしくは何も指定されていないように思われます。

**Comment by x022235** [comment]
ありがとうございます。
一応直してみました。

**Comment by x022235** [comment]
メモ。

### 原因
- EnumFontFamilies が返す値が Wine と Windows じゃ違う
  - Wine だとすべての charset が返される
  - Windows だと１つだけ
- EnumFontFamiliesEx はすべての charset のフォントを列挙する
  - Wine 上の EnumFontFamilies と同じ動作

### 修正方針
- Wine 独自のハックは入れたくない
  - テストめんどくさい
- 基本的に EnumFontFamilies を EnumFontFamiliesEx で置き換えて
  charset 違いのフォントを扱えるようにする
  - EnumFontFamiliesEx にすることで Wine と同じ動作になるので
    Wine 独自のハックにはならない
  - EnumFontFamilies は 16 ビットアプリの互換性のために用意されているので
    EnumFontFamiliesEx を使ったほうがいい
- 選択した文字セットを指定して EnumFontFamiliesEx するのは使えない
  - SHIFTJIS_CHARSET を指定して EnumFontFamiliesEx しても
    日本語フォントがない DotumChe などが列挙される
  - ANSI_CHARSET を指定して EnumFontFamiliesEx しても
    英語フォントがある HGゴシックM が列挙されない (HGゴシックE は列挙されるのに)
- デフォルトのフォントは `ＭＳ ゴシック` のまま
  - `IPAゴシック` とかにはしない
  - Linux で標準的なフォント名がわからない
  - 初回は設定してもらわないと行けない

### 修正内容
- EnumFontFamilies の使用箇所
  - `ChooseFontP::add_font_name` (ChooseFont.cc)
    - フォント名の列挙
    - フォント名が重複しないように修正
  - `FontSet::load_params` (font.cc)
    - xyzzy.ini から読み込んだフォントの charset の修正
    - xyzzy.ini に書いてある charset が存在しない場合にのみ
      charset を再設定するように修正
  - `ChooseFontP::add_font_size` (ChooseFont.cc)
    - フォントサイズの列挙
    - charset 違いの同じフォントが列挙されても問題ない
    - ANSI_CHARSET が無いフォント (HGゴシックM など) を選ぶとフォントサイズが空になるので
      修正が必要なんだけど面倒なので EnumFontFamilies のままにする
  - `print_settings::make_font` (print.cc)
    - フォントの存在チェック
    - charset 違いの同じフォントが列挙されても問題ない
    - いまいち何やっているのか分からないので EnumFontFamilies のままにする
- EnumFontFamiliesEx が返すフォントの順番はロケールを考慮したものになってそうなので
  単純に先頭のものを使うようにする (Wine も同じ)
  
  ```
  ＭＳ ゴシック [128]   # 128 = SHIFTJIS_CHARSET
  ＭＳ ゴシック [0]     #   0 = ANSI_CHARSET
  ＭＳ ゴシック [161]   # 161 = GREEK_CHARSET
  ＭＳ ゴシック [162]
  ＭＳ ゴシック [186]
  ＭＳ ゴシック [238]
  ＭＳ ゴシック [204]
  ```

### 非互換性
- 以下のフォントを設定できなくなる
  - `Courier New Baltic`
  - `Courier New CE`
  - `Courier New CYR`
  - `Courier New Greek`
  - `Courier New TUR`
- EnumFontFamiliesEx にしたことによる影響
- CE とかはチェコらしい。多分誰も使ってないと思うので気にしない

**Comment by x022235** [comment]
EnumFontFamilies テストプログラム。

``` c
#include <stdio.h>
#include <windows.h>

static int CALLBACK
enum_font_proc (ENUMLOGFONT *elf, NEWTEXTMETRIC *, int type, LPARAM lparam)
{
    if (*elf->elfLogFont.lfFaceName == '@'
        || (elf->elfLogFont.lfPitchAndFamily & 3) != FIXED_PITCH)
        return 1;

    char face[256];
    WideCharToMultiByte (CP_OEMCP, 0, elf->elfLogFont.lfFaceName, -1, face, 256, 0, 0);
    printf("%s [%d]\n", face, elf->elfLogFont.lfCharSet);
    (*((int *)lparam))++;

    return 1;
}

static void
print_font_families (HDC hdc)
{
    int n = 0;
    EnumFontFamilies (hdc, 0, FONTENUMPROC (enum_font_proc), LPARAM (&n));
    printf("-------- EnumFontFamilies %d\n\n", n);
}

static void
print_font_families_ex (HDC hdc, BYTE charset, char *charset_name)
{
    int n = 0;
    LOGFONT font;
    memset (&font, 0, sizeof (LOGFONT));
    font.lfCharSet = charset;
    EnumFontFamiliesEx (hdc, &font, FONTENUMPROC (enum_font_proc), LPARAM (&n), 0);
    printf("-------- EnumFontFamiliesEx (%s) %d\n\n", charset_name, n);
}

int main(int argc, char* argv[])
{
    HDC hdc = GetDC (0);

    print_font_families (hdc);
    print_font_families_ex (hdc, SHIFTJIS_CHARSET, "sjis");
    print_font_families_ex (hdc, ANSI_CHARSET, "ansi");
    print_font_families_ex (hdc, DEFAULT_CHARSET, "all");

    ReleaseDC (0, hdc);
    return 0;
}
```
