### ISSUE TITLE
フレーム・バーのコンテキストメニュー

### ISSUE THREAD

**Issue by rapidexp** [xyzzy-022/xyzzy#389]
フレーム並びの保存への対応ありがとうございます。

関連した要望ですが、バッファ・バー同様にフレーム・バーにもコンテキストメニューを用意いただけないでしょうか。

閉じたり名前変更しようとしたとき、つい直感的に右クリックしてしまう部分ですが、カスタマイズしようにも *frame-bar-context-menu-buffer* は実装されていないですよね？

ご検討よろしくお願いいたします。

**Comment by x022235** [comment]
とりあえずバッファバーと合わせて閉じるメニューを追加しました。
以下の変数でメニューをカスタマイズ出来ます。
- `*pseudo-frame-bar-context-menu*`
- `*pseudo-frame-bar-context-menu-frame*`
- `*pseudo-frame-bar-context-menu-handler*`
