### ISSUE TITLE
Google 日本語入力のカーソル周辺に入力モード表示がずれる

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#398]
xyzzy だとカーソル位置に表示されず、最後に日本語を入力した位置に表示されてしまい表示がずれる。
xyzzy を起動した直後は大丈夫だが一度日本語入力するとおかしくなる。

xyzzy 0.2.2.235 でも再現する。
メモ帳だとずれない。
- GoogleJapaneseInput-1.11.1515.0
- Windows 7

**Comment by coexe** [comment]
SKK日本語入力FEP作者のcoと申します。
拙作の日本語入力ソフトでも座標ずれが発生しておりましたため、
原因と修正方法を調査しましたのでご報告いたします。

disp.cc内のvoid Window::update_caretの末尾でset_ime_caretを実行していますが、
現在のコードではこれが意味をもっていません。その根拠は以下の通りです。

---

   SetCaretPos (app.active_frame.caret_pos.x,
               app.active_frame.caret_pos.y + app.text_font.size ().cy - h);
 /*\* @note
  コンポジション内での日本語変換中にはここは通らない。
  ここを通るのは、コンポジションが開放された後(入力確定の直後)である。
  通過の際はコンポジションは既に閉じており、app.ime_compositionは偽
  になっている。
  つまり、ここのset_ime_caretは意味のないコードになってしまっている。

  このままだと予測変換を行うタイプのIMEに悪影響を及ぼす。
  IMEからコンポジション座標を見ていると現在のカーソルの1つ前の位置に
  座標が遅れて出てくるように見える。この挙動はXyzzyだけのものであり、
  他のアプリと同様に動くよう修正すべきと考える。

  ImmSetCompositionWindowはapp.ime_compositionの状態に係らず常にアプ
  リ側のカーソル位置を指しておくのが筋と考える。
  よってset_ime_caret 内のapp.ime_compositonのフラグ判定処理そのもの
  を削除することで解決を図る。
  */
  set_ime_caret ();

---

そこで、toplev.ccのset_ime_caretに以下のようなパッチを当てることで
解決を図ります。この修正により、disp.cc側のset_ime_caretも意味を持つようになります。

---

void
set_ime_caret ()
{
－  if (app.active_frame.has_caret && app.ime_composition)
＋  if (app.active_frame.has_caret)
     {
      HIMC hIMC = app.kbdq.gime.ImmGetContext (app.toplev);

---

なにとぞよろしくお願いします。
