### ISSUE TITLE
ファイラ：　共通設定 「エアロスナップで変更した場合も保存」がファイラに適用されない

### ISSUE THREAD

**Issue by wkoiking** [xyzzy-022/xyzzy#406]
xyzzy 0.2.2 系列を使わせていただいております。

「共通設定」→「さまざまタブ」の「終了時のウィンドウサイズを保存」と「エアロスナップで変更した場合も保存」にチェックを入れても、ファイラは、エアロスナップで変更した場合、ウィンドウサイズが保存されません。

バグとは言えませんが、ファイラも位置＆サイズが保存された方が自然かと思います。

（ウィンドウキー+矢印キーのエアロスナップを多用しているので、ファイラの位置＆サイズが保存できるようになれば、嬉しいです。）

**Comment by x022235** [comment]
ファイラはあんまり使ってなかったので忘れてました＾＾
ファイラでもエアロスナップ時にウィンドウ位置を保存するようにします。

**Comment by wkoiking** [comment]
ありがとうございます。
もうxyzzyは手放せない状態なので、非常に助かります。

**Comment by x022235** [comment]
![aerosnap-filer](https://f.cloud.github.com/assets/1522408/1645488/ae1fd1f8-5901-11e3-8b2f-42d2fe3f74fd.png)
