### ISSUE TITLE
ウィンドウクラス名が "　" （全角スペース1文字）になっており使い勝手が悪い

### ISSUE THREAD

**Issue by tanaga9** [xyzzy-022/xyzzy#409]
ウィンドウクラス名は、半角スペースだけで構成して欲しい。
マルチバイト文字を使われると他のアプリケーションからウィンドウクラス名で検索する際に、文字コードが影響して使い勝手が悪い。
ちなみに、秀丸エディタは"HM32CLIENT"、sakura editorは"EditorClient"となっており、どちらもシングルバイト文字のみ使用。

そもそもウィンドウクラス名にマルチバイト文字を使っているアプリケーションを他に見たことがなく、また全角スペース1文字というのも「不可視」でありイマイチではないだろうか。

**Comment by x022235** [comment]
確かに不親切ですね。
ただ、変えるのは簡単なんですが互換性の崩れてしまうので悩ましい問題です。

**Comment by tanaga9** [comment]
分かりますが、そこをなんとか・・・
自前コンパイルはアップデートが面倒なのです。

**Comment by x022235** [comment]
引数とかxyzzy.iniで指定できるようにする対応でどうでしょうか？

**Comment by tanaga9** [comment]
siteinit.lに書けないので、それは必要ないかなと思います。

仕事上、使用マシンを点々とすることがあり、できるだけ設定を一元化して同じ使用感にしているのですが、異なるマシンでは違うユーザ名になり、xyzzy.iniの内容は新規扱いになります。
また、引数でiniの場所を指定し、必ず同じ引数で起動するようにしても、関連付けやWin7のタスクバーからの起動など、多様な起動方法の中にどうしても「引数の設定漏れ」が発生してしまうので、「次回起動時、あると思うな前回設定したini定義」と自分に言い聞かせています。

本件は最初からダメもとでOpenしておりますし、予想通りと言えます。
そもそも本家から枝分かれした3つのうち、まず他の2つに乗り換え、文字が見えなかったり色がつかなかったりエラーが出たりして、結局3つ目のここに安住した身ですので、シビアな互換性への姿勢はむしろ信頼に値するものです。

ですので、ここは一旦検討してみたという履歴を残してCloseするのもありかと思います。
