### ISSUE TITLE
バッファ選択ダイアログのソート順

### ISSUE THREAD

**Issue by rapidexp** [xyzzy-022/xyzzy#414]
バッファ選択ダイアログのソート順を、オプション指定できるか、前回の指定を記憶するかして欲しい。

セッションファイルで数十のファイルを一度に開き、フレームで簡易MVCのように使用しています。
例えばフレーム名 "Models" で F2 を押してバッファ選択を開いたときに期待するのは、同じフォルダにある別のモデルファイルですが、ソート順の初期値が名前のため同名のコントローラが周辺に集まってしまいます。

「モード」または「ファイル名」をクリックする一手間を省ければと思います。

**Comment by x022235** [comment]
![select-buffer-options](https://cloud.githubusercontent.com/assets/1522408/2777403/d50f9e6a-cae4-11e3-8df8-157b08c14c3f.png)

[共通設定]-[いろいろ]に設定を追加しました。
- ソート方法を保存をチェックした場合は前回バッファ選択ダイアログで指定したソート順でソートします。
- 前回のソート順が保存されていない場合や、保存しないように設定している場合はデフォルトのソート順でソートして表示します。
- あと、選択ダイアログのカラム名をクリックしても降順でのソートが出来なかったのでついでに対応しました。
