### ISSUE TITLE
reference.xml 内でのDTD 指定と中身の項目の不一致

### ISSUE THREAD

**Issue by hozmi** [xyzzy-022/xyzzy#417]
（初めまして）
 reference.xml のいくつかの項目で、そのファイルでの DTD の指定と異なっているところがありましたのでご報告します。
・seealso タグの出現位置
・type タグが必要
DTD の指定に揃える場合、下のようなパッチになると思います。ご参考まで。

<pre>
2721d2720
&lt; &lt;section&gt;変数と定数&lt;/section&gt;
2722a2722
&gt; &lt;section&gt;変数と定数&lt;/section&gt;
7129d7128
&lt; &lt;section&gt;入出力&lt;/section&gt;
7130a7130
&gt; &lt;section&gt;入出力&lt;/section&gt;
7184d7183
&lt; &lt;section&gt;入出力&lt;/section&gt;
7185a7185
&gt; &lt;section&gt;入出力&lt;/section&gt;
24415d24414
&lt; &lt;section&gt;バッファ&lt;/section&gt;
24416a24416
&gt; &lt;section&gt;バッファ&lt;/section&gt;
26552d26551
&lt; &lt;section&gt;データ型&lt;/section&gt;
26553a26553
&gt; &lt;section&gt;データ型&lt;/section&gt;
39426a39427
&gt; &lt;type&gt;Funtion&lt;/type&gt;
39446a39448
&gt; &lt;type&gt;Funtion&lt;/type&gt;
40936d40937
&lt; &lt;section&gt;入出力&lt;/section&gt;
40938a40940
&gt; &lt;section&gt;入出力&lt;/section&gt;
</pre>

**Comment by x022235** [comment]
ありがとうございます。直しました。

**Comment by hozmi** [comment]
早速の反映ありがとうございます。
また、反映後の reference.xml の type タグが閉じられていないようなのでご連絡します。

**Comment by x022235** [comment]
あぁ、すいません。。。
