### ISSUE TITLE
list-length の新たなバグ

### ISSUE THREAD

**Issue by coffee-p** [xyzzy-022/xyzzy#425]
ver 238 までは多分 (list-length '(2 3 . 5)) => 2 だった。
しかし、現在
(list-length '(2 5 . 3)) はエラーとなる。
list-length はソースレベルで循環リストの検証に使われる重要な関数である。早急な対策を望む。

**Comment by kosh04** [comment]
`list-length` の引数に proper list (cdr 部分が nil で終了しているリスト) あるいは循環リスト以外を渡した場合にエラーになる挙動は Common Lisp 仕様のようで、むしろ今まであったバグを修正したものかと思います。

参考： http://clhs.lisp.se/Body/f_list_l.htm

また、この挙動の修正は ver 0.2.2.236 にて行われたようです。
http://xyzzy-022.github.io/xyzzy/2012/03/29/xyzzy-0_2_2_236-release-note/

``` common-lisp
(list-length '(a . b))
=> 不正なデータ型です: b: list
```

**Comment by coffee-p** [comment]
kosh04さん、色々調べて下さったようでありがとうございます。小生の早トチリのようで撤回します。
しかし、まだ疑問があります。そもそも、小生か疑問を抱いたきっかけは  (last '(1 2 . 3))  がエラーをはくということでした。パニくった小生は list-length でもエラーになつたので v0.235のソース list.cc を(わかりもしないのに)見にいきました。そこには有名な兎と亀の論法らしきものが戴っていました。しかし、新にダウンロードしたV.253 には内部関数(?)の xlist_length は通常の length と同じ論法(list のlength)と同じようにみえたのです。つまり、last のバグが内部関数 xlist-length ではなく builtin の list-length だと早トチリしたわけです。さらに早トチリは暴走し、V238の改定によりバグが発生したと断定してしまいました。
小生の早トチリと刺激的なタイトルをつけたことをお詑びします。また、kosh04さんには御足労をおかけして申し訳ありませんでした。

**Comment by kosh04** [comment]
`list-length` の件は一応解決したかと思いますが、`(last '(1 2 . 3))` がエラーを吐くのは確かに奇妙ですね。本来なら `(2 . 3)` が返ってくるはず。
気になる場合は一旦この件はクローズして、改めて issue を立ててみてはどうでしょうか？
