### ISSUE TITLE
キーワードファイル更新

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#46]
デフォルトで付いてくるキーワードファイルを更新する。
- C
  - C99 対応
- C#
  - C# 5.0 対応
- C++
  - C++ 11 対応
- CSS
  - CSS level 3 対応
- HTML
  - HTML5 対応
- Perl
  - Perl 5 対応
- Java
  - Java5 対応
- Pascal
  - なんか色々追加
- Sql
  - なんか色々追加
  - DBMS 固有のキーワードを追加 (SQLServer, Oracle, MySQL, PostgreSQL)

以下のファイルはまた今度。
- Basic
- FORTRAN
- IDL
- TeX

**Comment by youz** [comment]
Perlですが、v5.10のsay, stateがアリならgiven, when, defaultも追加すると良いと思います。
http://perldoc.perl.org/feature.html

**Comment by x022235** [comment]
見落としてました。追加します。

**Comment by x022235** [comment]
追加しました。
