### ISSUE TITLE
load 時の *readtable* がファイルローカルではない

### ISSUE THREAD

**Issue by x022235** [xyzzy-022/xyzzy#64]
```
xyzzy では load 時に *readtable* に加えた変更はグローバルに影響するので、
interpol:disable-interpol-syntax を忘れると他のスクリプトにも影響を与えてしまうためです。

HyperSpec によると load は *readtable* をバインドしてからロードするのが仕様みたいなので
xyzzy のバグですかね。
```

http://d.hatena.ne.jp/miyamuko/20110919/p2

```
load binds *readtable* and *package* to the values they held before loading the file.
```

http://www.lispworks.com/documentation/HyperSpec/Body/f_load.htm#load
### 検討
- <del>ole.l で `set-dispatch-macro-character` しており、それに依存しているものもあるので
  修正は慎重に</del>
  - コメント参照
- `#{}` リーダマクロを利用しているアプリ
  - crylib
  - hatena-diary-mode
  - refer-for
  - translate
  - word-tools
  - xml-mode

**Comment by snmsts** [comment]
`*readtable*`のバインド自体、破壊可能なオブジェクトへのポインタである事はかわ`りないので、
ole.lはさくりとグローバルに影響を与えられるリードテーブルの破壊できて、
利用アプリも問題はないかと思われます。

**Comment by x022235** [comment]
あ、そうか。enable-hogehoge-syntax は copy-readtable してから
`*readtable*` をバインドしてるんですね。

確かに変更しても大丈夫そうですね。
ありがとうございます。
